version: "3.7"
services:
    jenkins:
        build: .
        env_file: .env
        ports:
            - "80:8080"

        ### Bind mount for JCasC config ###
        volumes:
            - type: bind
              source: ./jcasc.yml
              target: /jcasc/jcasc.yml
