unclassified:
  location:
    url: "http://localhost/"

jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      users:
      - id: ${ADMIN_USERNAME:-admin}
        password: ${ADMIN_PASSWORD:-admin}
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  remotingSecurity:
    enabled: true

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
- script: |
    job('Seed job') {
      triggers {
        hudsonStartupTrigger {
          label('')
          quietPeriod('')
          nodeParameterName('')
          runOnChoice('')
        }
      }
      scm {
        git {
          remote {
            github('AlexDexsoon/jenkins_the_ephemeral', 'https')
          }
        }
      }
      steps {
        jobDsl {
          targets('jobs/*/definition.groovy')
        }
      }
    }
