unclassified:
    location:
        url: "http://localhost/"

jenkins:
    authorizationStrategy:
        loggedInUsersCanDoAnything:
            allowAnonymousRead: false
    securityRealm:
        local:
            users:
                - id: ${ADMIN_USERNAME:-admin}
                  password: ${ADMIN_PASSWORD:-admin}

credentials:
    system:
        domainCredentials:
            - credentials:
                - basicSSHUserPrivateKey:
                    scope: GLOBAL
                    id: github_deploy_key
                    username: git
                    privateKeySource:
                        directEntry:
                            privateKey: ${GITHUB_DEPLOY_KEY}
                    passphrase: ${GITHUB_DEPLOY_KEY_PASSPHRASE}

security:
    globalJobDslSecurityConfiguration:
        useScriptSecurity: false

jobs:
    - script: >
          job('Seed job') {
              triggers {
                  hudsonStartupTrigger {
                      label('')
                      quietPeriod('')
                      nodeParameterName('')
                      runOnChoice('')
                  }
              }
              scm {
                  git {
                      remote {
                          github('zloyplohoy/jenkins_the_ephemeral', 'ssh')
                          credentials('github_deploy_key')
                      }
                  }
              }
              steps {
                  jobDsl {
                      targets('jobs/*/definition.groovy')
                  }
              }
          }
